py2030:
  profiles:
    client:
      monitor_config: false
      # midi_input_port: 1
      osc_outputs:
        # local:
        #   ip: '127.0.0.1'
        #   port: 2029
        #   # verbose: true
        controller_joiner:
          ip: '127.0.0.1'
          port: 2031
          outputs:
            - joins
          verbose: true
      join_interval: 2.0

      osc_inputs:
        self:
          ip: 'self'
          port: 2030
          shared: false
          verbose: true
          inputs:
            - effects
            - events
            - clips
        # local:
        #   ip: '127.0.0.1'
        #   port: 2030
        #   shared: false
        #   verbose: true
        #   inputs:
        #     - effects
        #     - events
        #     - clips
        # multi:
        #   ip: '224.0.20.30'
        #   port: 2030
        #   shared: true
        #   inputs:
        #     - effects
        #     - events
        #     - clips
      # http_server_port: 2032
      # broadcast_interval: 2.0
      # broadcast_reconfig: true
      download_reconfig: true

    controller:
      monitor_config: true
      # midi_input_port: 0
      osc_inputs:
        client_join_and_clip_receiver:
          ip: '127.0.0.1'
          port: 2031
          inputs:
            - joins
            - clips
          verbose: true
      osc_outputs:
        to_joiners:
          ip: 'joiner'
          port: 'joiner'
          verbose: true
          outputs:
            - events
            - effects
            - clips
      # osc_outputs:
        # local:
        #   ip: '127.0.0.1'
        #   port: 2030
        #   verbose: true
        # multi:
        #   ip: '224.0.20.30'
        #   port: 2030
        #   verbose: true
        # lancast:
        #   ip: '192.168.3.255'
        #   port: 2030
        # bcast:
        #   ip: '0.0.0.0'
        #   port: 2040
        #   verbose: true
        # bcast2:
        #   ip: '255.255.255.255'
        #   port: 2030
        # test1:
        #   ip: '192.168.1.10'
        #   port: 2030
        #   verbose: true
      # http_server_port: 2031
      # broadcast_interval: 2.0
      # broadcast_reconfig: true
      # download_reconfig: true

  midi_triggers:
    48: # C2
      effect:
        type: 'COLOR'
        r: 255
        g: 0
        b: 0
    60: # midi note: C3
      effect:
        type: 'COLOR'
        r: 0
        g: 255
        b: 0
  clients:
    1:
      ip: '192.168.1.13'
      name: 'local-tester'
    2:
      ip: '192.168.1.13'
      name: 'local-tester2'
    3:
      ip: '192.168.1.13'
      name: 'local-tester3'
