py2030:
  # version must have single quotes marks!
  version: '0.1.0'
  profiles:

    hoh:
      osc_inputs:
        self:
          ip: '' # self
          port: 2031
          verbose: true
      hoh_vid_starter:
        verbose: true
        vids:
          - '/home/pi/hoh/hoh-right-v06.mov'
          - '/home/pi/hoh/hoh-right-winjohn-v01.mov'
          - '/home/pi/hoh/hoh-right-wingeorgia-v01.mov'
          - '/home/pi/hoh/hoh-right-winmohammed-v01.mov'

    hohmidi:
      osc_outputs:
        bcast_and_local:
          # verbose: true
          # ip: 127.0.0.1
          ip: 192.168.2.255
          # hostname: 'rpi4.local'
          port: 2031
          outputs:
            - osc

      midi_input:
        port: 1
        verbose: true
        #   port: 1
        #   dummy: 'ok'
        map:
          # akai pads (prog1)
          144: # midi message type; note on
            36: # prog1, pad1
              osc: '/hoh/start/0'
            37:
              osc: '/hoh/start/1'
            38:
              osc: '/hoh/start/2'
            39:
              osc: '/hoh/start/3'
            40:
              osc: '/hoh/pause'
            41:
              osc: '/hoh/pause'
            42:
              osc: '/hoh/stop'
            43:
              osc: '/hoh/stop'

          # korg nano kontrol
            0: # prog1, pad1
              osc: '/hoh/start/1'
            9:
              osc: '/hoh/start/1'
            1:
              osc: '/hoh/start/2'
            10:
              osc: '/hoh/start/2'
            2:
              osc: '/hoh/start/3'
            11:
              osc: '/hoh/start/3'
            8:
              osc: '/hoh/start/0'
            17:
              osc: '/hoh/start/0'
            12:
              osc: '/hoh/pause'
            41:
              osc: '/hoh/pause'
            42:
              osc: '/hoh/stop'
            43:
              osc: '/hoh/stop'
          176:
            20:
              osc: '/hoh/pause'
            23:
              osc: '/hoh/stop'

    hohosc:
      osc_ascii_input:
        path: 'auto' # 'data/osc/clock_spot.csv'
        # loop: true
        # sync: true
        # verbose: true
      osc_outputs:
        localhost:
          ip: '192.168.2.255'
          port: 2031
          verbose: true
          outputs:
            - osc

    oscplayer:
      osc_ascii_input:
        path: 'auto' # 'data/osc/clock_spot.csv'
        # loop: true
        # sync: true
        # verbose: true
      osc_outputs:
        localhost:
          ip: '127.0.0.1'
          port: 2030
          verbose: true
          outputs:
            - osc

    mainstopper:
      osc_ascii_input:
        path: 'auto' # 'data/osc/clock_spot.csv'
        # loop: true
        # sync: true
        # verbose: true
      osc_outputs:
        localhost:
          hostname: 'rpi8.local'
          # ip: '127.0.0.1'
          port: 2031
          verbose: true
          outputs:
            - osc

    bridge:
      osc_outputs:
        bcast:
          ip: 192.168.2.255
          # hostname: 'rpi4.local'
          port: 2031
          outputs:
            - osc
        # local:
        #   ip: 127.0.0.1
        #   # hostname: 'rpi4.local'
        #   port: 2031
        #   verbose: true
        #   outputs:
        #     - osc
      osc_inputs:
        hallofheroes:
          ip: '' # '127.0.0.1'
          port: 2030
          verbose: true
          forwarder: true

    midi_old:
      osc_outputs:
        local:
          # verbose: true
          ip: 127.0.0.1
          # hostname: 'rpi4.local'
          port: 2030
          outputs:
            - osc
      midi_input:
        port: 1
        verbose: true
        #   port: 1
        #   dummy: 'ok'
        map:
          176:
            4:
              op: 'led'
          # yamaha 4x tom
          153:
            48: # tom1 (side A)
              osc-seq:
                - '/p/expo_bars1'
                - '/p/expo_bars2'
                - '/p/expo_bars3'
                - '/p/expo_bars4'
                - '/p/expo_bars5'
                - '/p/expo_bars6'
            47: # tom2 (side A)
              osc-seq:
                - '/p/expo2_1'
                - '/p/expo2_2'
                - '/p/expo2_3'
                - '/p/expo2_4'
                - '/p/expo2_5'
                - '/p/expo2_6'
            45: # tom3 (side B)
              osc-seq:
                - '/p/expo3_1'
                - '/p/expo3_2'
                - '/p/expo3_3'
                - '/p/expo3_4'
                - '/p/expo3_5'
                - '/p/expo3_6'
            43:
              osc-seq:
                - '/p/expo4_1'
                - '/p/expo4_2'
                - '/p/expo4_3'
                - '/p/expo4_4'
                - '/p/expo4_5'
                - '/p/expo4_6'
          # akai pads (prog1)
          144:
            36:
              osc-seq:
                - '/p/expo_bars1'
                - '/p/expo_bars2'
                - '/p/expo_bars3'
                - '/p/expo_bars4'
                - '/p/expo_bars5'
                - '/p/expo_bars6'
            # 36:
            #   osc: '/p/cursor1'
            37:
              osc: '/p/cursor2'
            38:
              osc: '/p/cursor3'
            39:
              osc: '/p/cursor4'
            40:
              osc: '/t/riser1'
            41:
              osc: '/t/riser2'
            42:
              osc: '/t/riser3'
            43:
              osc: '/t/riser4'
      # led:
      #   verbose: true
      #   device: '/dev/cu.usbserial-EN187350'
      #   channel_map:
      #     1: 2
      #     2: 3
      #     3: 4
      #     4: 5
