py2030:
  # version must have single quotes marks!
  version: '0.1.0'
  profiles:
    client:
      join_interval: 5.0
      osc_outputs:
        controller_joiner:
          # ip: '192.168.2.1'
          hostname: 'MarkBookPro.local'
          port: 2030
          outputs:
            - join
            - pong
          verbose: true
        of2030:
          ip: '127.0.0.1'
          port: 2031
          verbose: true
          outputs:
            - clip
            - song
            - osc
      osc_inputs:
        self:
          ip: '' #'self'
          port: 2030
          inputs:
            - ack
            - effect
            - event
            - clip
            - ping
            - restart

    test:
      join_interval: 5.0
      syncer:
        pong: true
        ping: false
      osc_outputs:
        controller_joiner:
          # ip: '127.0.0.1'
          hostname: 'MarkBookPro.local'
          port: 2030
          outputs:
            - join
            - pong
          verbose: true
        of2030:
          ip: '127.0.0.1'
          port: 2031
          outputs:
            - clip
            - song
            - osc
      osc_inputs:
        self:
          ip: ''
          port: 2025
          inputs:
            - ack
            - effect
            - event
            - clip
            - ping
            - restart
        of2030:
          ip: '' # '127.0.0.1'
          port: 2026
          verbose: true
          forwarder: true

    controller:
      osc_inputs:
        client_join_and_clip_receiver:
          ip: ''
          port: 2030
          inputs:
            - join
            - clip
            - pong
          verbose: true
        forwarder_for_all_osc_messages:
          ip: ''
          port: 2031
          forwarder: true
      osc_outputs:
        to_joiners:
          ip: 'joiner'
          port: 'joiner'
          verbose: true
          outputs:
            - event
            - effect
            - clip
            - ping
            - osc
        testpi:
          # ip: 'joiner'
          hostname: 'rpi2.local'
          port: '2031'
          # verbose: true
          outputs:
            - osc
      version_packager:
        enabled: true # dummy attribute
        source: 'py2030'
        destination: 'data/py2030-{version}.tar.gz'

    bridge:
      # midi_input:
      #   verbose: true
      #   port: 1
      #   dummy: 'ok'
      osc_inputs:
      #   self:
      #     ip: '' # '127.0.0.1'
      #     port: 2029
      #     # verbose: true
      #     forwarder: true
        self_and_maxosc:
          ip: '' # '127.0.0.1'
          port: 2030
          verbose: true
          forwarder: true
          # osc_map format:
          # <osc addr>:
          #   <first param value>: <osc message to be triggered>
          osc_map:
            '/inloop':
              127: '/p/inloop.start'
              0: '/p/inloop.start'
            '/impro':
              127: '/p/impro.start'
              1: '/p/impro.finalize'
            '/stellar':
              127: '/p/stellar.start'
              126: '/p/stellar.end'
              0: '/p/stellar.worms'
              1: '/p/stellar.spot_grow'
              2: '/p/stellar.clock1'
              3: '/p/stellar.clock2'
              4: '/p/stellar.clock3'
              5: '/p/stellar.clock4'
              6: '/p/stellar.clock5'
              7: '/p/stellar.clock6'
              8: '/p/stellar.clock7'
              9: '/p/stellar.map'
              # 10: '/p/stellar.voice1' # now live
              11: '/p/stellar.chorus' # two spots and smoke
              12: '/p/stellar.ping'
              # 13: '/p/stellar.voice2' # also turns on steady (non-blinking) spot
            '/live':
              0: '/p/stellar.voice1'
              1: '/p/stellar.voice2'
            '/scav':
              127: '/p/scav.start'
              126: '/p/scav.end'
              # 0: '/p/scav.fans'
              1: '/p/scav.fans'
              2: '/p/scav.fanbeat'
              3: '/p/scav.pano'
              4: '/p/scav.turbo'
              5: '/p/scav.roof'
              6: '/p/scav.fallingline'
            '/leap':
              'forward': '/cfg/rings_pattern_white_intro/current_alpha'
            '/rings':
              127: '/p/rings.start'
              126:  '/p/rings.end'
              0: '/p/rings.fade'
              1: '/p/rings.march1'
              2: '/p/rings.hey1'
              3: '/p/rings.circles'
              4: '/p/rings.squares'
              5: '/p/rings.chorus.beat'
              6: '/p/rings.hey2'
              7: '/p/rings.hey3' # also start verse
              8: '/p/rings.verse2.2'
              9: '/p/rings.verse2.2.2'
              10: '/p/rings.blackblocks'
              11: '/p/rings.chorus2'
              12: '/p/rings.hey4' # also start onregelmatigheid
              13: '/p/rings.hey5' # also start bridge
              14: '/p/rings.snare'
              15: '/p/rings.roll'
              16: '/p/rings.chorus3'
              17: '/p/rings.chorus1.start'
              18: '/p/rings.chorus1.end'
              19: '/p/rings.chorus2.end'
              20: '/p/rings.chorus4.start'
            # '/live' [pitch]:
            '/mud':
              0: '/p/mud.wheel'
              1: '/p/mud.machinebuild'
              2: '/p/mud.machineloop'
              3: '/p/mud.roof1'
              4: '/p/mud.roof2'
              5: '/p/mud.destruct'
            '/lava':
              127: '/p/lava.start'
              # 126: '/p/lava.end' # <-- geruik lava.flatline voor end
              0: '/p/lava.beat'
              1: '/p/lava.bed1'
              2: '/p/lava.grow'
              3: '/p/lava.flatline'
              4: '/p/lava.nightmare'
              5: '/p/lava.blink'
              6: '/p/lava.chorus1.end'
            '/dead':
              127: '/p/dead.start'
            '/rain':
              126: '/p/rain.end'
              0: '/p/rain.thunder'
              1: '/p/rain.noorderlicht'
              2: '/p/rain.tear'
              3: '/p/rain.cubes'
            '/divide':
              127: '/p/divide.start'
              126: '/p/divide.end'
              0: '/p/divide.chords'
              1: '/p/divide.particles1'
              # 2: '/p/divide.particles1move'
              3: '/p/divide.particles2'
              4: '/p/divide.particles3'
              5: '/p/divide.blinks'

      osc_outputs:
        bcast:
          ip: 192.168.2.255
          # hostname: 'rpi4.local'
          port: 2031
          outputs:
            - osc
        # local:
        #   ip: 127.0.0.1
        #   # hostname: 'rpi4.local'
        #   port: 2031
        #   outputs:
        #     - osc
        # rpi10:
        #   # ip: 192.168.2.255
        #   hostname: 'rpi10.local'
        #   port: 2031
        #   outputs:
        #     - osc
        # rpi3:
        #   # ip: 192.168.2.255
        #   hostname: 'rpi3.local'
        #   port: 2031
        #   outputs:
        #     - osc
        # rpi4:
        #   # ip: 192.168.2.255
        #   hostname: 'rpi4.local'
        #   port: 2031
        #   outputs:
        #     - osc
        # rpi5:
        #   # ip: 192.168.2.255
        #   hostname: 'rpi5.local'
        #   port: 2031
        #   outputs:
        #     - osc
        # rpi7:
        #   # ip: 192.168.2.255
        #   hostname: 'rpi7.local'
        #   port: 2031
        #   outputs:
        #     - osc
        # rpi8:
        #   # ip: 192.168.2.255
        #   hostname: 'rpi8.local'
        #   port: 2031
        #   outputs:
        #     - osc
        # rpi4:
        #   # ip: 192.168.2.255
        #   hostname: 'rpi4.local'
        #   port: 2031
        #   outputs:
        #     - osc


    everything:
      # monitor_config: true
      # midi_input_port: 0
      # http_server_port: 2040
      # broadcast_interval: 3.0
      # broadcast_reconfig: true
      # download_reconfig: true
      of2030:
        # path: '/home/pi/of2030' # default
        log_monitor_interval: 20.0
        log_monitor_treshold: 20.0
      alive_notifier:
        file: 'last-alive.txt'
        interval: 15.0
      downloader:
        enabled: true
        reconfig: true
        version: true
      syncer:
        pong: true
        ping: false
      osc_inputs:
        self:
          ip: '' #'self'
          port: 2030
          shared: false
          verbose: true
          inputs:
            - ack
            - effect
            - event
            - clip
            - ping
            - restart

    oscrecorder:
      osc_inputs:
        receiver:
          ip: '127.0.0.1'
          port: 2031
          forwarder: true
      osc_ascii_output:
        path: auto
        verbose: true
        trim: true

    oscplayer:
      osc_ascii_input:
        path: 'auto' # 'data/osc/clock_spot.csv'
        # loop: true
        # sync: true
        # verbose: true
      osc_outputs:
        # localhost:
        #   ip: '127.0.0.1'
        #   port: 2031
        #   verbose: true
        #   outputs:
        #     - osc
        bcast:
          ip: 192.168.2.255
          # hostname: 'rpi4.local'
          port: 2031
          outputs:
            - osc
        max_dev:
          ip: 192.168.2.100
          # hostname: 'rpi4.local'
          port: 2030
          outputs:
            - osc
        # rpi2:
        #   hostname: 'rpi2.local'
        #   port: 2031
        #   outputs:
        #     - osc

    osccfg:
      osc_inputs:
        remote_receiver:
          ip: '' #'127.0.0.1'
          port: 2029
          forwarder: true
          # verbose: true
      osc_outputs:
        forward_local:
          ip: '127.0.0.1'
          port: 2031
          # verbose: true
          outputs:
          - osc
      config_recorders:
        screens:
          prefix: '/scr'
          path: 'data/screens.xml'
          configs_root_el: 'screens'
          config_el: 'screen'
          # verbose: true
        effects:
          prefix: '/cfg'
          path: 'data/effects.xml'
          configs_root_el: 'effects'
          config_el: 'effect'
          # verbose: true

  midi_triggers:
    48: # C2
      effect:
        type: 'COLOR'
        r: 255
        g: 0
        b: 0
    60: # midi note: C3
      effect:
        type: 'COLOR'
        r: 0
        g: 255
        b: 0
