py2030:
  # version must have single quotes marks!
  version: '0.1.0'
  profiles:
    client:
      join_interval: 5.0
      osc_outputs:
        controller_joiner:
          # ip: '192.168.2.1'
          hostname: 'MarkBookPro.local'
          port: 2030
          outputs:
            - join
            - pong
          verbose: true
        of2030:
          ip: '127.0.0.1'
          port: 2031
          verbose: true
          outputs:
            - clip
            - song
            - osc
      osc_inputs:
        self:
          ip: '' #'self'
          port: 2030
          inputs:
            - ack
            - effect
            - event
            - clip
            - ping
            - restart

    test:
      join_interval: 5.0
      syncer:
        pong: true
        ping: false
      osc_outputs:
        controller_joiner:
          # ip: '127.0.0.1'
          hostname: 'MarkBookPro.local'
          port: 2030
          outputs:
            - join
            - pong
          verbose: true
        of2030:
          ip: '127.0.0.1'
          port: 2031
          outputs:
            - clip
            - song
            - osc
      osc_inputs:
        self:
          ip: ''
          port: 2025
          inputs:
            - ack
            - effect
            - event
            - clip
            - ping
            - restart
        of2030:
          ip: '' # '127.0.0.1'
          port: 2026
          verbose: true
          forwarder: true

    controller:
      osc_inputs:
        client_join_and_clip_receiver:
          ip: ''
          port: 2030
          inputs:
            - join
            - clip
            - pong
          verbose: true
        forwarder_for_all_osc_messages:
          ip: ''
          port: 2031
          forwarder: true
      osc_outputs:
        to_joiners:
          ip: 'joiner'
          port: 'joiner'
          verbose: true
          outputs:
            - event
            - effect
            - clip
            - ping
            - osc
        testpi:
          # ip: 'joiner'
          hostname: 'rpi2.local'
          port: '2031'
          # verbose: true
          outputs:
            - osc
      version_packager:
        enabled: true # dummy attribute
        source: 'py2030'
        destination: 'data/py2030-{version}.tar.gz'

    bridge:
      osc_inputs:
        self:
          ip: '' # '127.0.0.1'
          port: 2029
          # verbose: true
          forwarder: true
        maxosc:
          ip: '' # '127.0.0.1'
          port: 2030
          # verbose: true
          forwarder: true
      osc_outputs:
        # rpi10:
        #   # ip: 192.168.2.255
        #   hostname: 'rpi10.local'
        #   port: 2031
        #   outputs:
        #     - osc
        # rpi3:
        #   # ip: 192.168.2.255
        #   hostname: 'rpi3.local'
        #   port: 2031
        #   outputs:
        #     - osc
        # rpi4:
        #   # ip: 192.168.2.255
        #   hostname: 'rpi4.local'
        #   port: 2031
        #   outputs:
        #     - osc
        # rpi5:
        #   # ip: 192.168.2.255
        #   hostname: 'rpi5.local'
        #   port: 2031
        #   outputs:
        #     - osc
        # rpi7:
        #   # ip: 192.168.2.255
        #   hostname: 'rpi7.local'
        #   port: 2031
        #   outputs:
        #     - osc
        # rpi8:
        #   # ip: 192.168.2.255
        #   hostname: 'rpi8.local'
        #   port: 2031
        #   outputs:
        #     - osc
        bcast:
          ip: 192.168.2.255
          # hostname: 'rpi4.local'
          port: 2031
          outputs:
            - osc
        local:
          ip: 127.0.0.1
          # hostname: 'rpi4.local'
          port: 2031
          outputs:
            - osc
        # rpi4:
        #   # ip: 192.168.2.255
        #   hostname: 'rpi4.local'
        #   port: 2031
        #   outputs:
        #     - osc


    everything:
      # monitor_config: true
      # midi_input_port: 0
      # http_server_port: 2040
      # broadcast_interval: 3.0
      # broadcast_reconfig: true
      # download_reconfig: true
      of2030:
        # path: '/home/pi/of2030' # default
        log_monitor_interval: 20.0
        log_monitor_treshold: 20.0
      alive_notifier:
        file: 'last-alive.txt'
        interval: 15.0
      downloader:
        enabled: true
        reconfig: true
        version: true
      syncer:
        pong: true
        ping: false
      osc_inputs:
        self:
          ip: '' #'self'
          port: 2030
          shared: false
          verbose: true
          inputs:
            - ack
            - effect
            - event
            - clip
            - ping
            - restart

    oscrecorder:
      osc_inputs:
        receiver:
          ip: '127.0.0.1'
          port: 2031
          forwarder: true
      osc_ascii_output:
        path: auto
        verbose: true
        trim: true

    oscplayer:
      osc_ascii_input:
        path: 'auto' # 'data/osc/clock_spot.csv'
        # loop: true
        # sync: true
        # verbose: true
      osc_outputs:
        localhost:
          ip: '127.0.0.1'
          port: 2031
          # verbose: true
          outputs:
            - osc
        bcast:
          ip: 192.168.2.255
          # hostname: 'rpi4.local'
          port: 2031
          outputs:
            - osc
        # rpi2:
        #   hostname: 'rpi2.local'
        #   port: 2031
        #   outputs:
        #     - osc

    osccfg:
      osc_inputs:
        remote_receiver:
          ip: '' #'127.0.0.1'
          port: 2029
          forwarder: true
          # verbose: true
      osc_outputs:
        forward_local:
          ip: '127.0.0.1'
          port: 2031
          # verbose: true
          outputs:
          - osc
      config_recorders:
        screens:
          prefix: '/scr'
          path: 'data/screens.xml'
          configs_root_el: 'screens'
          config_el: 'screen'
          # verbose: true
        effects:
          prefix: '/cfg'
          path: 'data/effects.xml'
          configs_root_el: 'effects'
          config_el: 'effect'
          # verbose: true

  midi_triggers:
    48: # C2
      effect:
        type: 'COLOR'
        r: 255
        g: 0
        b: 0
    60: # midi note: C3
      effect:
        type: 'COLOR'
        r: 0
        g: 255
        b: 0
