py2030:
  profiles:
    client:
      monitor_config: false
      download_reconfig: true
      join_interval: 2.0
      syncer:
        pong: true
        ping: false
      osc_outputs:
        # local:
        #   ip: '127.0.0.1'
        #   port: 2029
        #   # verbose: true
        controller_joiner:
          ip: '127.0.0.1'
          port: 2030
          outputs:
            - join
            - pong
          verbose: true

      osc_inputs:
        self:
          ip: 'self'
          port: 2030
          shared: false
          verbose: true
          inputs:
            - ack
            - effect
            - event
            - clip
            - ping

    controller:
      monitor_config: true
      # midi_input_port: 0
      # http_server_port: 2031
      # broadcast_interval: 2.0
      # broadcast_reconfig: true
      # download_reconfig: true
      syncer:
        pong: false
        ping: true

      osc_inputs:
        client_join_and_clip_receiver:
          ip: '127.0.0.1'
          port: 2030
          inputs:
            - join
            - clip
            - pong
          verbose: true
        forwarder_for_all_osc_messages:
          ip: '127.0.0.1'
          port: 2031
          forwarder: true
      osc_outputs:
        to_joiners:
          ip: 'joiner'
          port: 'joiner'
          verbose: true
          outputs:
            - event
            - effect
            - clip
            - ping
            - osc

    oscrecorder:
      osc_inputs:
        receiver:
          ip: '127.0.0.1'
          port: 2031
          forwarder: true
      osc_ascii_output:
        path: auto
        verbose: true
        trim: true

    oscplayer:
      osc_ascii_input:
        path: 'auto' # 'data/osc/clock_spot.csv'
        # loop: true
        # sync: true
        verbose: true
      osc_outputs:
        playbacker:
          ip: '127.0.0.1'
          port: 2031
          verbose: true
          outputs:
            - event
            - effect
            - clip
            - ping
            - osc
        to_joiners:
          ip: 'joiner'
          port: 'joiner'
          verbose: true
          outputs:
            - event
            - effect
            - clip
            - ping
            - osc

    osccfg:
      osc_inputs:
        receiver:
          ip: 'self' #'127.0.0.1'
          port: 2029
          forwarder: true
          verbose: true
      osc_outputs:
        # to_joiners:
        #   ip: 'joiner'
        #   port: 'joiner'
        #   verbose: true
        #   outputs:
        #     - event
        #     - effect
        #     - clip
        #     - ping
        #     - osc
        local_cfg_forward:
          ip: '127.0.0.1'
          port: 2031
          verbose: false
          outputs:
          - osc
      config_recorders:
        screens:
          prefix: '/scr'
          path: 'data/screens.xml'
          configs_root_el: 'screens'
          config_el: 'screen'



  midi_triggers:
    48: # C2
      effect:
        type: 'COLOR'
        r: 255
        g: 0
        b: 0
    60: # midi note: C3
      effect:
        type: 'COLOR'
        r: 0
        g: 255
        b: 0
