py2030:
  # local of2030 data
  #osc_folder: '/Users/mark/Dropbox/2030-mark/19-timelines/4-OSC-EXPORTS'

  of2030:
    path: '/Users/mark/code/of_v0.9.3_osx_release/apps/of2030/of2030'

  remotes:
    rpi10:
      hostname: 'rpi10'
      ofbuilder: true
    rpi3:
      hostname: 'rpi3'
    rpi4:
      hostname: 'rpi4'
    rpi5:
      hostname: 'rpi5'
    rpi7:
      hostname: 'rpi7'
    rpi8:
      hostname: 'rpi8'
    rpi2:
      hostname: 'rpi2'
